name: 🤖 Auto dependency review
on:
  pull_request:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Dependency Review
        uses: actions/dependency-review-action@v3.0.6
        with:
          fail-on-severity: critical
