name: 🤖 Auto remove label on closed issue
on:
  issues:
    types: [closed]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: 'state: need triage'
