name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  typecheck:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs
      - name: Typecheck
        run: npm run typecheck

  cspell:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs
      - name: Spell checks code
        run: npm run cspell -- --no-progress

  prettier:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TINKOFF_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run prettier
        run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: ./.github/actions/auto-push

  stylelint:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TINKOFF_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run stylelint
        run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: ./.github/actions/auto-push

  eslint:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup global variables
        uses: ./.github/actions/variables

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TINKOFF_BOT_PAT }}

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Run eslint
        run: npm run lint ${{ env.RUN_AUTOFIX == 'true' && '-- --fix' || '' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: ./.github/actions/auto-push

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
