name: Nightly publish

on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

env:
  NX_BRANCH: ${{ github.event.number }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

jobs:
  build:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Packages
    runs-on: ubuntu-latest
    env:
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Build
        run: npm run run-many:build:libs

      - name: Publish dev builds
        run: npx ts-node ./scripts/publish-dev-builds.ts

concurrency:
  group: publish-dev-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
