name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    # At 11:00 on Tuesday (UTC+8)
    - cron: '0 3 * * 2'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.68.0
        with:
          token: ${{ secrets.TINKOFF_BOT_PAT }}
          configurationFile: renovate.json
        env:
          LOG_LEVEL: 'debug'
